### ISSUE TITLE
Operational Range

### ISSUE THREAD

**Issue by herosheets-codeship** [herosheets/woin-starships#49] opened 2015-09-20 18:38 UTC
Operational range I still don't know how that's being calculated, but it should be (Class^3) \* FTL fuel efficiency.

**Comment by jsomara** [comment] 2015-09-20 22:45
I think this is working as intended, with the caveat that if your fuel efficiency is 0, it reports 0

Example:
Hull Class 2
1x Carter Psitech EL-1 liquid fuel rocket (power: 50 ; SPEED: 25.0 ; fuel efficiency: 0.5 )

2^ 3 \* 0.5 = 4

However, if you don't have a fuel efficiency rating, I'll make it multiply your hull class ^ 3 \* 1, instead of 0

**Comment by Morrus** [comment] 2015-09-20 23:02
It’s not. 

I just quickly tried a thing. Added an FTL engine.  Added a second FTL engine and the range doubled. 

Jordan, I appreciate all your efforts, and I think you guys are doing a wonderful job, but this particular thing has been an issue for ages now, and it’s such a simple calculation.  It’s trivial, I promise!  I’ve brought it up half a dozen times now!  It’s so, so, so simple!

I understand that my explanations might not be clear enough for a programmer.  I’m not used to talking to computer programmers.

Image attached.

Somewhere you have something other than (Class^3)_fuel efficiency in your equation.  If you look at that calculation in your system, I’m sure you’ll see it’s not just (Class^3)_fuel efficiency.

I’d love to knock this issue on the head, but honestly, I’ve been bringing it up for months now! You repeatedly mark it as “resolved” without resolving it!

We’re so close.  Just a couple of little things to fix. This is one of them!

**Closed as completed** 2015-09-21 01:24 UTC
